package com.tres.wedding.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="runbookEntry")
public class RunbookEntry extends Model {

	private String runbookEntryId;

	private String runbookId;

	private String name;

	private String description;

	private String comment;

	private String time;

	private RunbookTasks tasks;

	@DynamoDBAutoGeneratedKey
	@DynamoDBHashKey
	public String getRunbookEntryId() {
		return runbookEntryId;
	}

	public void setRunbookEntryId(String runbookEntryId) {
		this.runbookEntryId = runbookEntryId;
	}

	@DynamoDBRangeKey
	public String getRunbookId() {
		return runbookId;
	}

	public void setRunbookId(String runbookId) {
		this.runbookId = runbookId;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getComment() {
		return comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public String getTime() {
		return time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	public RunbookTasks getTasks() {
		return tasks;
	}

	public void setTasks(RunbookTasks tasks) {
		this.tasks = tasks;
	}



}
