package com.tres.wedding.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="task")
public class Task extends Model {

	private String taskId;

	private String partyId;

	private String userId;

	private String runbookId;

	private Subtasks subTasks;

	private String name;

	private String description;

	private String comment;

	@DynamoDBAutoGeneratedKey
	@DynamoDBHashKey
	@DynamoDBIndexHashKey(globalSecondaryIndexName = "task-assigned-to-user")
	public String getTaskId() {
		return taskId;
	}

	public void setTaskId(String taskId) {
		this.taskId = taskId;
	}

	@DynamoDBIndexRangeKey(localSecondaryIndexName="task-by-party")
	public String getPartyId() {
		return partyId;
	}

	public void setPartyId(String partyId) {
		this.partyId = partyId;
	}

	public String getUserId() {
		return userId;
	}

	@DynamoDBIndexRangeKey(globalSecondaryIndexName="task-assigned-to-user")
	public void setUserId(String userId) {
		this.userId = userId;
	}

	@DynamoDBRangeKey
	public String getRunbookId() {
		return runbookId;
	}

	public void setRunbookId(String runbookId) {
		this.runbookId = runbookId;
	}

	public Subtasks getSubTasks() {
		return subTasks;
	}

	public void setSubTasks(Subtasks subTasks) {
		this.subTasks = subTasks;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getComment() {
		return comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
